/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package me.miltz.labelprinter;

import static org.junit.Assert.*;

import org.junit.Test;

public class AppTest {

  @Test
  public void testAppHasAGreeting() {
    App classUnderTest = new App();
    assertNotNull("App should be constructible", classUnderTest);
  }
}
