/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package me.miltz.labelprinter;

import java.io.IOException;

public class App {

  public static void main(String[] args) throws IOException {
    var rec = new Recipient(
      "Franz Miltz",
      new String[] { "Kirschallee 32", "03099 Kolkwitz" }
    );
    var recs = new Recipient[24];
    for (int i = 0; i < 24; i++) {
      recs[i] = rec;
    }
    var builder = new Builder(Config.defaultConfig());
    var doc = builder.build(recs);
    doc.save("demo.pdf");
    doc.close();
  }
}
