/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package me.miltz.labelprinter;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.nio.charset.StandardCharsets;

public class App {

  public static void main(String[] args) throws IOException {
    // Determining the input file
    if (args.length < 2) {
      System.err.println("ERROR: Missing required arguments.");
      System.err.println("Usage: label-printer <input.xml> <output.pdf>");
      return;
    }
    final File inFile = new File(args[0]);
    final File outFile = new File(args[1]);
    // Reading the input
    final byte[] data = new byte[(int) inFile.length()];
    try (var fis = new FileInputStream(inFile);) {
      int numRead = fis.read(data);
      if (numRead <= 0) {
        throw new IOException();
      }
    }
    // Building output
    final String str = new String(data, StandardCharsets.UTF_8);
    final var config = Config.defaultConfig();
    final var parser = new Parser(config);
    final var recs = parser.parse(str);
    final var builder = new Builder(config);
    final var doc = builder.build(recs);
    // Writing output
    doc.save(outFile);
    doc.close();
  }
}
